### ISSUE TITLE
大佬，能给个具体点的部署流程嘛？不会用lua的

### ISSUE THREAD

**Issue by sayri23** [feilongproject/Qbot_res#1]
大佬，能给个具体点的部署流程嘛？不会用lua的

**Comment by feilongproject** [comment]
> 大佬，能给个具体点的部署流程嘛？不会用lua的

这是OPQ_BOT的插件，详情可以见[https://github.com/OPQBOT/OPQ](https://github.com/OPQBOT/OPQ)，里面的wiki有详细教程

**Comment by sayri23** [comment]
> > 大佬，能给个具体点的部署流程嘛？不会用lua的
> 
> 这是OPQ_BOT的插件，详情可以见https://github.com/OPQBOT/OPQ，里面的wiki有详细教程

opq我会用，我是学python的，不大清楚lua写的插件怎么用

**Comment by feilongproject** [comment]
> > > 大佬，能给个具体点的部署流程嘛？不会用lua的
> > 
> > 
> > 这是OPQ_BOT的插件，详情可以见[https://github.com/OPQBOT/OPQ，里面的wiki有详细教程](https://github.com/OPQBOT/OPQ%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84wiki%E6%9C%89%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B)
> 
> opq我会用，我是学python的，不大清楚lua写的插件怎么用

lua插件OPQ是原生支持的，只需要把插件添加到主目录下的Plugins文件夹里就行

**Comment by sayri23** [comment]
好的，谢谢~
